packages:
  - packages/@conf-ts/*
  - packages/@conf-ts/compiler-native/npm/*
  - packages/playground

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - webpack@5.107.1
  - '@types/node@26.0.0'

onlyBuiltDependencies:
  - esbuild
  - sharp
