/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Capture a filesystem-backed TypeScript project without loading TypeScript. */
export declare function createMacroProjectSnapshot(entryFiles: Array<string>, snapshotOptions?: JsMacroProjectSnapshotOptions | undefined | null): JsProjectSnapshot

export interface JsMacroProjectSnapshotOptions {
  compilerOptions?: any
  previous?: JsProjectSnapshot
  overrides?: Record<string, string>
}

export interface JsProjectSnapshot {
  files: Record<string, string>
  resolutions?: Record<string, Record<string, string>>
  compilerOptions?: any
  entryFiles?: Array<string>
  dependencies?: Array<string>
  referencedModules?: Record<string, Array<string>>
  missingDependencies?: Array<string>
}

export interface JsTransformInput {
  filename: string
  code: string
  project?: JsProjectSnapshot
}

export interface JsTransformOptions {
  env?: Record<string, string>
  inheritProcessEnv?: boolean
  quote?: 'single' | 'double'
  preserveKeyOrder?: boolean
  sourceMap?: boolean
}

export interface JsTransformProjectInput {
  project: JsProjectSnapshot
  files?: Array<string>
}

/** Return static import/export specifiers for a set of source overrides. */
export declare function scanReferencedModules(files: Record<string, string>): Record<string, Array<string>>

/** Evaluate @conf-ts/macro calls and return ordinary TypeScript source. */
export declare function transform(input: JsTransformInput, transformOptions?: JsTransformOptions | undefined | null): TransformResult

/** Transform a project with one shared native analysis pass. */
export declare function transformProject(input: JsTransformProjectInput, transformOptions?: JsTransformOptions | undefined | null): TransformProjectResult

export interface TransformProjectResult {
  transformed: Record<string, TransformResult>
  dependencies: Array<string>
}

export interface TransformResult {
  code: string
  map: Record<string, any> | null
  dependencies: Array<string>
}
