/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Pre-evaluate macros then compile a TypeScript config file to JSON/YAML. */
export declare function compile(inputFile: string, format: string, options?: JsCompileOptions | undefined | null): CompileResult

/** Pre-evaluate macros then compile from in-memory files to JSON/YAML. */
export declare function compileInMemory(files: Record<string, string>, entryFile: string, format: string, options?: JsCompileOptions | undefined | null): CompileResult

export interface CompileResult {
  output: string
  dependencies: Array<string>
}

export interface JsCompileOptions {
  preserveKeyOrder?: boolean
  jsx?: boolean
  env?: Record<string, string>
  jsxOutput?: JsxOutputOptions
  quote?: 'single' | 'double'
}

export interface JsxOutputOptions {
  type?: string
  props?: string | boolean
  children?: string | boolean
  key?: string
  fragment?: string
  typeFormat?: 'string' | 'descriptor'
}

/** Pre-evaluate macros in a filesystem project using the oxc API. */
export declare function transformMacros(inputFile: string, options?: JsCompileOptions | undefined | null): TransformResult

/** Pre-evaluate macros in an in-memory oxc project. */
export declare function transformMacrosInMemory(files: Record<string, string>, entryFile: string, options?: JsCompileOptions | undefined | null): TransformResult

export interface TransformResult {
  files: Record<string, string>
  dependencies: Array<string>
}
