/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsProjectSnapshot {
  files: Record<string, string>
  resolutions?: Record<string, Record<string, string>>
  compilerOptions?: any
  entryFiles?: Array<string>
  dependencies?: Array<string>
}

export interface JsTransformInput {
  filename: string
  code: string
  project?: JsProjectSnapshot
}

export interface JsTransformOptions {
  env?: Record<string, string>
  quote?: 'single' | 'double'
  preserveKeyOrder?: boolean
  jsx?: boolean
  jsxOutput?: any
  sourceMap?: boolean
}

/** Evaluate @conf-ts/macro calls and return ordinary TypeScript source. */
export declare function transform(input: JsTransformInput, transformOptions?: JsTransformOptions | undefined | null): TransformResult

export interface TransformResult {
  code: string
  map: Record<string, any> | null
  dependencies: Array<string>
}
