/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compile a TypeScript config file to JSON or YAML. */
export declare function compile(inputFile: string, format: string, options?: JsCompileOptions | undefined | null): CompileResult

/** Compile from in-memory files. */
export declare function compileInMemory(files: Record<string, string>, entryFile: string, format: string, macroMode: boolean, options?: JsCompileOptions | undefined | null): CompileResult

export interface CompileResult {
  output: string
  dependencies: Array<string>
}

export interface JsCompileOptions {
  preserveKeyOrder?: boolean
  macroMode?: boolean
  env?: Record<string, string>
}
