/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compile ordinary TypeScript source to JSON or YAML. */
export declare function compile(input: string | JsSourceCompileInput, format: string, options?: JsCompileOptions | undefined | null): CompileResult

/** Compile an in-memory ordinary TypeScript project. */
export declare function compileInMemory(files: Record<string, string>, entryFile: string, format: string, tsconfig?: JsTsConfig | undefined | null, options?: JsCompileOptions | undefined | null): CompileResult

export interface CompileResult {
  output: string
  dependencies: Array<string>
}

export interface JsCompileOptions {
  preserveKeyOrder?: boolean
}

export interface JsSourceCompileInput {
  filename: string
  code: string
  project?: JsSourceProject
}

export interface JsSourceProject {
  files: Record<string, string>
  resolutions?: Record<string, Record<string, string>>
  compilerOptions?: any
}

export interface JsTsConfig {
  compilerOptions?: any
}
