/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compare two conf.ts source projects and their optional evaluated JSON values. */
export declare function diffProjects(left: JsDiffProject, right: JsDiffProject, options?: JsDiffOptions | undefined | null): any

export interface JsDiffOptions {
  arrayKeys?: Record<string, string>
  redact?: Array<string>
  redactAll?: boolean
  includeSource?: boolean
  maxMatchWork?: number
}

export interface JsDiffProject {
  filename: string
  code: string
  files?: Record<string, string>
  evaluated?: any
  dependencies?: Array<string>
  evaluationError?: string
}
